### ISSUE TITLE
应用启动异常，缺少图标

### ISSUE THREAD

**Issue by waliguder** [oncework/kuaixieya#10]
```
Error: Image could not be created from /Applications/快写鸭.app/Contents/Resources/app/dist/assets/trayTemplate.png
    at Object.init (/Applications/快写鸭.app/Contents/Resources/app/dist/main.bundle.js:759:70711)
    at App.<anonymous> (/Applications/快写鸭.app/Contents/Resources/app/dist/main.bundle.js:543:61795)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

---

kuaixieya 1.2.3
Electron 9.3.4
darwin 19.6.0
Locale: en-US

**Comment by xudaolong** [comment]
@waliguder 不好意思 更新了下脚本 最新包已更新哈~

**Comment by waliguder** [comment]
可以了，大佬
