### ISSUE TITLE
更新到1.2.3报错了？？

### ISSUE THREAD

**Issue by yanwen** [oncework/kuaixieya#11]
```
Error: Image could not be created from /Applications/快写鸭.app/Contents/Resources/app/dist/assets/trayTemplate.png
    at Object.init (/Applications/快写鸭.app/Contents/Resources/app/dist/main.bundle.js:759:70711)
    at App.<anonymous> (/Applications/快写鸭.app/Contents/Resources/app/dist/main.bundle.js:543:61795)
```

---

kuaixieya 1.2.3
Electron 9.3.4
darwin 19.6.0
Locale: en-US

**Comment by xudaolong** [comment]
@yanwen 已更新。重新下载一次看看？ #10
