### ISSUE TITLE
Windows 11 Crash

### ISSUE THREAD

**Issue by PlutoNameless** [oncework/kuaixieya#12]
```
TypeError: Cannot read property 'show' of undefined
    at MainWindow.show (D:\Program\kuaixieya\resources\app\dist\main.bundle.js:375459:33)
    at Tray.<anonymous> (D:\Program\kuaixieya\resources\app\dist\main.bundle.js:374533:34)
    at Tray.emit (events.js:223:5)
```

---

kuaixieya 1.1.0
Electron 9.3.4
win32 10.0.22000
Locale: zh-CN

**Comment by xudaolong** [comment]
@Thiece 会影响使用吗
