### ISSUE TITLE
Cannot read property 'isVisibleOnAllWorkspaces' of undefined

### ISSUE THREAD

**Issue by edisonwd** [oncework/kuaixieya#13]
关闭应用重新打开时报错：
```
TypeError: Cannot read property 'isVisibleOnAllWorkspaces' of undefined
    at Object.show (C:\Users\AppData\Local\Programs\kuaixieya\resources\app\dist\main.bundle.js:67:168607)
    at App.<anonymous> (C:\Users\AppData\Local\Programs\kuaixieya\resources\app\dist\main.bundle.js:543:61921)
    at App.emit (events.js:223:5)
```

---

kuaixieya 1.2.3
Electron 9.3.4
win32 10.0.19042
Locale: zh-CN

**Comment by xudaolong** [comment]
@edisonwd 会影响使用吗

**Comment by edisonwd** [comment]
> @edisonwd 会影响使用吗
无法打开应用，显示如下图：
![image](https://user-images.githubusercontent.com/25941671/135383069-ddb2eefb-2922-4d39-aa80-c6fa4b8c89a1.png)

**Comment by edisonwd** [comment]
卸载后重新安装就可以了

**Comment by xudaolong** [comment]
@edisonwd 就是更新的时候不行是吗

**Comment by edisonwd** [comment]
> @edisonwd 就是更新的时候不行是吗

不是更新的时候不行，是发布到简书不成功，关闭退出后，重新打开就报出如上错误

**Comment by xudaolong** [comment]
@edisonwd ok 知道问题啦 下个小版本修复
