### ISSUE TITLE
打开出问题

### ISSUE THREAD

**Issue by waliguder** [oncework/kuaixieya#14]
```
Error: Image could not be created from /Applications/快写鸭.app/Contents/Resources/app/dist/assets/trayTemplate.png
    at Object.init (/Applications/快写鸭.app/Contents/Resources/app/dist/main.bundle.js:759:70711)
    at App.<anonymous> (/Applications/快写鸭.app/Contents/Resources/app/dist/main.bundle.js:543:61795)
```

---

kuaixieya 1.2.3
Electron 9.3.4
darwin 19.6.0
Locale: en-US

**Comment by xudaolong** [comment]
@waliguder 请使用最新版本
