### ISSUE TITLE
codeecpander Error

### ISSUE THREAD

**Issue by lihao58619** [oncework/kuaixieya#16]
```
TypeError: Cannot read property 'data' of undefined
    at D:\Program Files\Codeexpander\resources\app\app\main.bundle.js:2:4300499
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async s.refreshTokenFn (D:\Program Files\Codeexpander\resources\app\app\main.bundle.js:2:4299797)
    at async Object.pollerGiteeToken (D:\Program Files\Codeexpander\resources\app\app\main.bundle.js:2:4302968)
    at async Timeout.<anonymous> (D:\Program Files\Codeexpander\resources\app\app\main.bundle.js:2:4303100)
```

---

electron-software-repo 4.0.2
Electron 11.5.0
win32 10.0.22000
Locale: zh-CN

**Comment by xudaolong** [comment]
@lihao58619 描述一下操作行为 有gif更好哈

**Comment by xudaolong** [comment]
@lihao58619 已修复
