### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by xxhk-org** [oncework/kuaixieya#17]
```
TypeError: Cannot read property 'data' of undefined
    at C:\Users\LeoCh\AppData\Local\Programs\Codeexpander\resources\app\app\main.bundle.js:2:4300698
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async s.refreshTokenFn (C:\Users\LeoCh\AppData\Local\Programs\Codeexpander\resources\app\app\main.bundle.js:2:4299996)
    at async Object.pollerGiteeToken (C:\Users\LeoCh\AppData\Local\Programs\Codeexpander\resources\app\app\main.bundle.js:2:4303167)
    at async Timeout.<anonymous> (C:\Users\LeoCh\AppData\Local\Programs\Codeexpander\resources\app\app\main.bundle.js:2:4303299)
```

---

electron-software-repo 4.0.7
Electron 11.5.0
win32 10.0.22000
Locale: zh-CN

**Comment by xudaolong** [comment]
@LeoChanXY 使用一下微信登录试试
