### ISSUE TITLE
csdn初始化渠道配置报错

### ISSUE THREAD

**Issue by Petterpx** [oncework/kuaixieya#9]
`Unhandled Promise Rejection
Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:87:1542)
    at electron/js2c/renderer_init.js:139:429
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:123:346)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)`

**Comment by Petterpx** [comment]
mac端

**Comment by xudaolong** [comment]
@Petterpx 开发环境没问题的 晚点我看看

**Comment by xudaolong** [comment]
@Petterpx 1.2.1。版本修复了哇
